[workspace]
members = [
  # "wasmi-fibonacci/script",
  # "wain-fibonacci/script",
  "fibonacci/script",
  "fibonacci/program"
  # "revm/script",
]
resolver = "2"

[workspace.package]
version = "1.1.0"
edition = "2021"

[workspace.dependencies]
sp1-zkvm = { path = "../sp1/crates/zkvm/entrypoint" }
sp1-sdk = { path = "../sp1/crates/sdk", default-features = false }
sp1-build = { path = "../sp1/crates/build", default-features = false }
