[workspace]
[package]
name = "wasmi-fibonacci-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev"}
sp1-derive = "1.1.0"
wasmi = "0.36.0"
wat = "1.216.0"
