[workspace]
[package]
name = "wain-fibonacci-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "dev"}
wain-exec = "0.3"
wain-syntax-binary = "0.1.5"
